# Generated by Django 2.0.2 on 2018-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Synopsis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_poster', verbose_name='Image')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'verbose_name': 'Movie',
            },
        ),
    ]
