# Generated by Django 2.0.2 on 2018-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180220_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='movie-slug', unique=True, verbose_name='Movie Slug'),
        ),
    ]
